import sys
from pathlib import Path

# Ensure the project root is on the Python path so 'main' can be imported
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import streamlit as st
import matplotlib.pyplot as plt
import pandas as pd

from main import OkavangoData

#1. Page configuration and Title
st.set_page_config(page_title="Environmental Maps | Project Okavango", layout="wide")
st.title("Project Okavango - Environmental Analysis")

#2. Initialize the Class with cache to prevent reloading on every interaction
@st.cache_resource
def load_data():
    return OkavangoData()

with st.spinner('Processing the latest datasets...'):
    try:
        data_handler = load_data()
    except Exception as e:
        st.error(f"Error loading data: {e}")
        st.stop()

#Access the merged maps dictionary generated by your class
available_maps = data_handler.merged_maps

if not available_maps:
    st.error("No maps were found. Please check the 'downloads' folder.")
    st.stop()

#3. Dropdown menu to select the dataset
dataset_names = list(available_maps.keys())
chosen_map = st.selectbox("Select the Dataset you want to visualize:", dataset_names)

#Get the GeoDataFrame corresponding to the user's choice
gdf_current = available_maps[chosen_map]

#Filter out null values for visualization purposes
gdf_plot = gdf_current.dropna(subset=['value'])

#Dynamically find the most recent year
if not gdf_plot.empty:
    recent_year = int(gdf_plot['Year'].max())
    st.info(f"Showing the most recent data available. Reference year: **{recent_year}**.")

#4. Plot the Interactive World Map
st.subheader(f"Interactive Map: {chosen_map}")

import plotly.express as px

if not gdf_plot.empty:
    #Create the interactive choropleth map
    fig = px.choropleth(
        gdf_plot,
        geojson=gdf_plot.geometry,
        locations=gdf_plot.index,
        color="value",
        hover_name="Entity",
        color_continuous_scale="viridis",
        projection="natural earth"
    )
    
    #Clean up the map background and layout
    fig.update_geos(fitbounds="locations", visible=False)
    fig.update_layout(
        margin={"r":0,"t":0,"l":0,"b":0},
        geo=dict(bgcolor='rgba(0,0,0,0)')
    )
    
    #Display the interactive map in Streamlit
    st.plotly_chart(fig, use_container_width=True)
else:
    st.warning("No data available to generate the map.")

#5. Graph: Top 5 and Bottom 5 Countries
st.subheader("Top 5 and Bottom 5 Countries")
if not gdf_plot.empty:
    #Sort the data from highest to lowest value
    df_sorted = gdf_plot.sort_values(by='value', ascending=False)
    
    #Extract the top 5 and bottom 5
    df_graph = pd.concat([df_sorted.head(5), df_sorted.tail(5)])

    fig2, ax2 = plt.subplots(figsize=(10, 5))
    
    #Colors: Green for Top 5, Red for Bottom 5
    colors = ['#2ca02c']*5 + ['#d62728']*5 
    
    #Create the bar chart
    ax2.bar(df_graph['Entity'].astype(str), df_graph['value'], color=colors)
    ax2.set_ylabel("Recorded Value")
    ax2.set_title(f"Extremes for: {chosen_map}")
    
    #Rotate country names for better readability
    plt.xticks(rotation=45, ha='right')
    st.pyplot(fig2)
else:
    st.warning("Not enough data to generate the chart.")

#6. Country Specific Details
st.subheader("Country Specific Data")

#Get a clean, sorted list of all countries available in the current dataset
available_countries = gdf_plot['Entity'].dropna().unique().tolist()
available_countries.sort()

#Create a dropdown menu for countries
chosen_country = st.selectbox("Select a country to see exact details:", ["None"] + available_countries)

#Display the specific value if a country is selected
if chosen_country != "None":
    #Filter the dataframe for the selected country
    country_data = gdf_plot[gdf_plot['Entity'] == chosen_country]
    
    #Extract the exact value and year
    if not country_data.empty:
        specific_value = country_data['value'].iloc[0]
        specific_year = int(country_data['Year'].iloc[0])
        
        #Show a nice metric box on the dashboard
        st.metric(label=f"Recorded value for {chosen_country} (Year: {specific_year})", value=round(specific_value, 2))