import streamlit as st
import matplotlib.pyplot as plt
import pandas as pd
import sys
import os

# Add the parent directory to the path so we can import main.py from the root folder
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from main import OkavangoData

# 1. Page configuration and Title
st.set_page_config(page_title="Project Okavango", layout="wide")
st.title("Project Okavango - Environmental Analysis")

# 2. Initialize the Class with cache to prevent reloading on every interaction
@st.cache_resource
def load_data():
    return OkavangoData()

with st.spinner('Processing the latest datasets...'):
    try:
        data_handler = load_data()
    except Exception as e:
        st.error(f"Error loading data: {e}")
        st.stop()

# Access the merged maps dictionary generated by your class
available_maps = data_handler.merged_maps

if not available_maps:
    st.error("No maps were found. Please check the 'downloads' folder.")
    st.stop()

# 3. Dropdown menu to select the dataset
dataset_names = list(available_maps.keys())
chosen_map = st.selectbox("Select the Dataset you want to visualize:", dataset_names)

# Get the GeoDataFrame corresponding to the user's choice
gdf_current = available_maps[chosen_map]

# Filter out null values for visualization purposes
gdf_plot = gdf_current.dropna(subset=['value'])

# Dynamically find the most recent year
if not gdf_plot.empty:
    recent_year = int(gdf_plot['Year'].max())
    st.info(f"Showing the most recent data available. Reference year: **{recent_year}**.")

# 4. Plot the World Map
st.subheader(f"Map: {chosen_map}")
fig, ax = plt.subplots(1, 1, figsize=(15, 8))

# Base map with a neutral color for countries without data
gdf_current.plot(ax=ax, color='lightgrey', edgecolor='black', linewidth=0.2)

# Overlay the actual data
if not gdf_plot.empty:
    gdf_plot.plot(column='value', ax=ax, legend=True,
                  legend_kwds={'label': "Value", 'orientation': "horizontal"},
                  cmap='viridis', edgecolor='black', linewidth=0.2)

ax.set_axis_off()
st.pyplot(fig)

# 5. Graph: Top 5 and Bottom 5 Countries
st.subheader("Top 5 and Bottom 5 Countries")
if not gdf_plot.empty:
    # Sort the data from highest to lowest value
    df_sorted = gdf_plot.sort_values(by='value', ascending=False)
    
    # Extract the top 5 and bottom 5
    df_graph = pd.concat([df_sorted.head(5), df_sorted.tail(5)])

    fig2, ax2 = plt.subplots(figsize=(10, 5))
    
    # Colors: Green for Top 5, Red for Bottom 5
    colors = ['#2ca02c']*5 + ['#d62728']*5 
    
    # Create the bar chart
    ax2.bar(df_graph['Entity'].astype(str), df_graph['value'], color=colors)
    ax2.set_ylabel("Recorded Value")
    ax2.set_title(f"Extremes for: {chosen_map}")
    
    # Rotate country names for better readability
    plt.xticks(rotation=45, ha='right')
    st.pyplot(fig2)
else:
    st.warning("Not enough data to generate the chart.")